### PR TITLE
166240777 allow user to register

### PR DESCRIPTION
**Pull request by alainburindi**
### What does this PR do?
 ``` allow user to register``` 
##### Description of Task to be completed?
* create register component
* Create alert component
##### How should this be manually tested?
* Clone the repos
* Install dependencies ```npm install```
* Run ```npm run start```
* gon on ```localhost:8080/register``` to signup
##### What are the relevant pivotal tracker stories?
[#166240777](https://www.pivotaltracker.com/story/show/166240777)

### CODE REVIEW

**Comment by alainburindi** [comment]
Screen Shot 2019-08-03 at 07 03 41

**Comment by alainburindi** [comment]
Screen Shot 2019-08-07 at 17 55 41

Validation

**Review by nkpremices — APPROVED** [review]
Good job man

**Comment by truestbyheart** [comment]
please resolve the conflict

**Pull request merged**
